services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      args:
        # Frontend talks to backend via Nginx proxy at /api
        VITE_API_BASE_URL: /api
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge