services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: contactdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tiger
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d contactdb"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contactdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiger
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      args:
        # Frontend talks to backend via Nginx proxy at /api
        VITE_API_BASE_URL: /api
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  db-data: